printWidth = 80
useTabs = false
semi = false
singleQuote = true
quoteProps = "as-needed"
jsxSingleQuote = false
trailingComma = "all"
bracketSpacing = true
bracketSameLine = false
arrowParens = "always"
requirePragma = false
insertPragma = false
proseWrap = "preserve"
htmlWhitespaceSensitivity = "css"
endOfLine = "lf"
embeddedLanguageFormatting = "auto"
